version: '3'
services:
  server:
    build: "./server"
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"
  
  prediction:
    build: "./prediction"
    ports:
      - "8080:8080"

  visualization:
    build: "./visualization"
    ports:
      - "8888:8888"
  
  statistics:
    build: "./statistics"
    ports:
      - "8111:8111"