version: '3'
services:
  server:
    build: "./server"
    ports:
      - "8000:8000"
  
  prediction:
    build: "./prediction"
    ports:
      - "8080:8080"

  visualization:
    build: "./visualization"
    ports:
      - "8888:8888"